# Generated by Django 3.1.1 on 2021-08-14 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='countview',
            name='last_updated',
            field=models.TimeField(auto_now=True),
        ),
    ]
