# Generated by Django 3.1.1 on 2021-08-14 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_countview_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countview',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
