# Generated by Django 3.1.1 on 2021-08-14 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_auto_20210814_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countview',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
