# Generated by Django 3.1.1 on 2021-08-09 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0017_members_popularitem1_popularitem2_popularitem3'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationStoreUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_latitude', models.CharField(max_length=200)),
                ('user_longitude', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LocationStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_latitude', models.CharField(max_length=200)),
                ('shop_longitude', models.CharField(max_length=200)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.shop')),
            ],
        ),
    ]
