# Generated by Django 3.1.1 on 2021-08-10 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LocationStoreUsers',
            new_name='LocationStoreUser',
        ),
    ]
