# Generated by Django 3.1.1 on 2021-08-11 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20210811_0834'),
        ('location_manager', '0002_auto_20210810_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationstore',
            name='Name',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='locationstore',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.shop'),
        ),
    ]
