# Generated by Django 3.1.1 on 2021-08-13 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_manager', '0003_auto_20210811_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='searchQueries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
