# Generated by Django 3.1.1 on 2021-08-19 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location_manager', '0005_auto_20210813_1506'),
    ]

    operations = [
        migrations.DeleteModel(
            name='searchQueries',
        ),
    ]
