# Generated by Django 3.1.7 on 2021-08-05 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=80, unique=True)),
                ('Image', models.ImageField(default='CatImage/default.jpg', upload_to='CatImage')),
            ],
        ),
        migrations.CreateModel(
            name='Shop_Img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='ShopImg')),
                ('image2', models.ImageField(upload_to='ShopImg')),
                ('image3', models.ImageField(upload_to='ShopImg')),
                ('image4', models.ImageField(upload_to='ShopImg')),
                ('image5', models.ImageField(upload_to='ShopImg')),
                ('image6', models.ImageField(upload_to='ShopImg')),
                ('image7', models.ImageField(upload_to='ShopImg')),
                ('image8', models.ImageField(upload_to='ShopImg')),
                ('image9', models.ImageField(upload_to='ShopImg')),
                ('image10', models.ImageField(upload_to='ShopImg')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, unique=True)),
                ('About', models.TextField(default='Nothing')),
                ('opening', models.TimeField()),
                ('closing', models.TimeField()),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.IntegerField(max_length=15)),
                ('city', models.CharField(max_length=100)),
                ('location', models.TextField()),
                ('Image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.shop_img')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='Sub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subcategory'),
        ),
    ]
