# Generated by Django 3.1.1 on 2021-08-05 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='Image',
        ),
        migrations.RemoveField(
            model_name='category',
            name='Sub',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='Image',
            field=models.ImageField(default='CatImage/default.jpg', upload_to='CatImage'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='Sub',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.category'),
            preserve_default=False,
        ),
    ]
