# Generated by Django 3.1.1 on 2021-08-05 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_shop_display_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='Image',
        ),
        migrations.AlterField(
            model_name='shop_img',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='ShopImg'),
        ),
        migrations.AlterField(
            model_name='shop_img',
            name='image10',
            field=models.ImageField(blank=True, null=True, upload_to='ShopImg'),
        ),
        migrations.AlterField(
            model_name='shop_img',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='ShopImg'),
        ),
        migrations.AlterField(
            model_name='shop_img',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='ShopImg'),
        ),
        migrations.AlterField(
            model_name='shop_img',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='ShopImg'),
        ),
        migrations.AlterField(
            model_name='shop_img',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='ShopImg'),
        ),
        migrations.AlterField(
            model_name='shop_img',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to='ShopImg'),
        ),
        migrations.AlterField(
            model_name='shop_img',
            name='image7',
            field=models.ImageField(blank=True, null=True, upload_to='ShopImg'),
        ),
        migrations.AlterField(
            model_name='shop_img',
            name='image8',
            field=models.ImageField(blank=True, null=True, upload_to='ShopImg'),
        ),
        migrations.AlterField(
            model_name='shop_img',
            name='image9',
            field=models.ImageField(blank=True, null=True, upload_to='ShopImg'),
        ),
        migrations.CreateModel(
            name='ShopView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(blank=True, null=True)),
                ('code1', models.TextField(blank=True, null=True)),
                ('code2', models.TextField(blank=True, null=True)),
                ('code3', models.TextField(blank=True, null=True)),
                ('Images', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.shop_img')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.shop')),
            ],
        ),
    ]
