# Generated by Django 3.1.1 on 2021-08-05 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210805_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='Items',
            field=models.IntegerField(default=0),
        ),
    ]
