# Generated by Django 3.1.1 on 2021-08-06 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210805_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='Approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shop',
            name='Cancelled',
            field=models.BooleanField(blank=True, default=False),
            preserve_default=False,
        ),
    ]
