# Generated by Django 3.1.1 on 2021-08-06 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210806_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='Cancelled',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
