# Generated by Django 3.1.1 on 2021-08-07 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Contact',
            new_name='phone',
        ),
    ]
