# Generated by Django 3.1.1 on 2021-08-08 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0013_auto_20210807_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='user',
        ),
        migrations.AddField(
            model_name='shop',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shop',
            name='products_added',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_sharable_id', models.CharField(max_length=20)),
                ('user_secret', models.CharField(max_length=50)),
                ('is_cafe', models.BooleanField(default=False)),
                ('cafe_secret_key', models.CharField(blank=True, max_length=50, null=True)),
                ('is_half_kyc_verified', models.BooleanField(default=False)),
                ('is_full_kyc_verified', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.IntegerField()),
                ('message', models.TextField()),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.shop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(max_length=120)),
                ('Product_Image', models.ImageField(upload_to='product_image')),
                ('Product_M_R_P', models.IntegerField()),
                ('Product_Price', models.IntegerField()),
                ('Specifications', models.TextField()),
                ('About_Product', models.TextField()),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.shop')),
            ],
            options={
                'ordering': ('-added',),
            },
        ),
        migrations.AddField(
            model_name='shop',
            name='user_details',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.userdetails'),
            preserve_default=False,
        ),
    ]
