# Generated by Django 3.1.1 on 2021-08-08 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_shop_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='user_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.userdetails'),
        ),
    ]
