# Generated by Django 3.1.1 on 2021-08-11 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20210809_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='location_succeed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='payment_succeed',
            field=models.BooleanField(default=False),
        ),
    ]
