# Generated by Django 3.1.1 on 2021-08-11 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20210811_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='user_secret',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='user_sharable_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
