# Generated by Django 3.1.1 on 2021-08-11 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20210811_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopview',
            name='about_sitution',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
