# Generated by Django 3.1.1 on 2021-08-11 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20210811_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.shop'),
        ),
        migrations.AlterField(
            model_name='member',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.userdetails'),
        ),
        migrations.AlterField(
            model_name='shopview',
            name='shop',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.shop'),
        ),
    ]
