# Generated by Django 3.1.1 on 2021-08-11 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20210811_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopview',
            name='shop',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.shop'),
        ),
    ]
