# Generated by Django 3.1.1 on 2021-08-12 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20210811_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.shop'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.userdetail'),
            preserve_default=False,
        ),
    ]
