# Generated by Django 3.1.1 on 2021-08-12 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_auto_20210812_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='About',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='shopview',
            name='about',
            field=models.CharField(max_length=200),
        ),
    ]
