# Generated by Django 3.1.1 on 2021-08-13 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_auto_20210812_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='About_Product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Product_Image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Product_Price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Specifications',
        ),
        migrations.DeleteModel(
            name='ProductReview',
        ),
    ]
