# Generated by Django 3.1.1 on 2021-08-14 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_auto_20210813_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='payment_initialized',
            field=models.BooleanField(default=False),
        ),
    ]
