# Generated by Django 3.1.1 on 2021-08-16 06:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_userdetail_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
