# Generated by Django 3.1.1 on 2021-08-18 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_userdetail_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
