# Generated by Django 3.1.1 on 2021-08-21 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_userdetail_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
