# Generated by Django 3.1.1 on 2021-08-21 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_userdetail_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='user_viewed',
            field=models.BooleanField(default=False),
        ),
    ]
