# Generated by Django 3.1.1 on 2021-08-21 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_contact_user_viewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='Username',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
