# Generated by Django 3.1 on 2021-08-26 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_offertimeline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offertimeline',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterField(
            model_name='offertimeline',
            name='Product_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
