# Generated by Django 3.1 on 2021-08-26 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_auto_20210826_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='offertimeline',
            name='shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.shop'),
            preserve_default=False,
        ),
    ]
