# Generated by Django 3.1.1 on 2021-08-14 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='trans_id',
            field=models.CharField(default=1, max_length=14),
            preserve_default=False,
        ),
    ]
