# Generated by Django 3.1.1 on 2021-08-14 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_manager', '0002_transaction_trans_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='trans_id',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
