# Generated by Django 3.1.1 on 2021-08-16 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_manager', '0005_auto_20210814_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='offer_available',
            field=models.BooleanField(default=True),
        ),
    ]
